name: Terraform Infra Pipeline

on:
  push:
    branches:
      - staging
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write PEM and PUB Keys to File
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          echo "${{ secrets.EC2_PUBLIC_KEY }}" > key.pub
          chmod 600 key.pem key.pub

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.ref == 'refs/heads/staging'
        run: |
          terraform plan \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="key_name=${{ secrets.KEY_NAME }}" \
            -var="private_key_path=key"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="key_name=${{ secrets.KEY_NAME }}" \
            -var="private_key_path=key"